[package]
name = "deimos-core"
version = "0.1.0"
authors = ["snsvrno <snsvrno@tuta.io>"]
edition = "2018"
exclude = ["src/test_macros"]

[dependencies]
failure = "0.1"
failure_derive = "0.1"

[features]
dev-testing = []