[package]
name = "lua-interpreter"
version = "0.1.0"
authors = ["snsvrno <snsvrno@tuta.io>"]
edition = "2018"

[dependencies]
failure = "0.1"

[dev-dependencies]
lua-test = { version = "*", path = " ../../../lua-test" }
